### ISSUE TITLE
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable....

### ISSUE THREAD

**Issue by Nova-Scotia** [R-ArcGIS/r-bridge#40] opened 2020-06-29 20:12 UTC
I'm trying to access feature classes from ArcGIS Online and/or from features stored on local file geodatabases. Previously, I could connect to these successfully using R V. 4.0.0 and ArcGIS Pro V. 2.4. I recently upgraded to Pro 2.5.2... but now I get an error, but only with some of my feature classes.

Here's my code that used to work without complaining:
```
library(arcgisbinding)
arc.check_product()
pilot_locs <- arc.data2sf(arc.select(arc.open("Maps/Basemap/Basemap.gdb/Locations")))
```

**Here's my code + output, including the error that is now occurring:**

```
> library(arcgisbinding)
*** Please call arc.check_product() to define a desktop license.
> arc.check_product()
product: ArcGIS Pro (12.5.0.22081)
license: Advanced
version: 1.0.1.240 
> 
> pilot_locs <- arc.data2sf(arc.select(arc.open("Maps/Basemap/Basemap.gdb/Locations")))
```
**ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.**
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arcgisbinding_1.0.1.240

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       rstudioapi_0.11    magrittr_1.5       units_0.6-6        tidyselect_1.1.0   R6_2.4.1          
 [7] rlang_0.4.6        dplyr_1.0.0        tools_4.0.0        grid_4.0.0         packrat_0.5.0      KernSmooth_2.23-17
[13] e1071_1.7-3        DBI_1.1.0          ellipsis_0.3.0     class_7.3-17       tibble_3.0.1       lifecycle_0.2.0   
[19] sf_0.9-4           crayon_1.3.4       purrr_0.3.4        vctrs_0.3.0        glue_1.4.0         compiler_4.0.0    
[25] pillar_1.4.4       generics_0.0.2     classInt_0.4-3     pkgconfig_2.0.3   

```

**Comment by orhuna** [comment] 2020-06-29 20:27
@Nova-Scotia sorry to hear that you are having this issue. We have an internal tracking issue for this one and the cause of it is changes in RGDAL that we have not factored into `arcgisbinding` yet. As we work on the fix here is a workaround :

```
points <- arc.select(arc.open("Maps/Basemap/Basemap.gdb/Locations"))
## Pop X and Y using arc.shape and Store 
shape_info <- arc.shape(points) 
pilot_locs <- cbind(shape_info$x, shape_info$y)
```

**Comment by orhuna** [comment] 2020-06-29 20:28
This is a known internal bug. Tracking on this external issue.

**Comment by Nova-Scotia** [comment] 2020-06-29 20:33
Thanks @orhuna, that helps for now...

**Comment by Nova-Scotia** [comment] 2020-06-29 20:47
As in, I can't seem to use st_as_sf with those output coordinates to get back an sf object. It complains about negative subscripts.

**Comment by orhuna** [comment] 2020-08-12 13:50
@Nova-Scotia this bug is fixed on the latest version, `v241`

**Closed** 2021-07-30 17:49 UTC
